services:
  - type: web
    name: securiguide-backend
    env: python
    region: oregon  # or change to frankfurt if you're in Europe
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    rootDir: backend
